apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-test-app
spec:
  template:
    spec:
      containers:
        - name: cpu-stress
          image: busybox
          command: ["sh", "-c", "for i in $(seq 1 180); do echo hi; sleep 1; done"]
      restartPolicy: Never
