apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
